[Playground] Migration 8.x.x to 15.x.x (#253)
* Removed ontimize dependencies

* Removed unnecesary dependencies

* Updated to Angular 9

* Removed @angular/flex-layout

* Updates the Angular CDK to v9

* Updated "ngx-highlightjs": "^4.1.1

* Migration to Angular 10

* Updated Angular Material to version 10

* Removed package-lock

* Updated jasmine-core

* Updated to Angular 11

* Updated to Material 11

* Updated    "highlight.js": "^11.7.0",

* Updated package.json

* Migration to Angular 12

* Updates Angular Material to v12

* Updated to Angular 13

* Updated Angular Material to version 13

* Update to  Angular version 14

* Updates the Angular Material to v14.

* Updated to Angular v15

* Updates the Angular Material to v15.

* ng generate @angular/material:mdc-migration

* Package "@angular/material-moment-adapter" has a missing peer dependency of "moment" @ "^2.18.1".

* Removed hammer.js reference

* Added ontimize-web-ngx dependencies and rxjs, tslib,zone.js versions

* Replaced InputConverter by BooleanInputConverter

* Updated sonar action

* Updated browserslistrc

* Added ClipboardModule

* Refactor import theme and angular.json configuration

* Fixed input and output

* Fixed bug in dark mode toggle

* Resolving todo(md-migration)

* Improved styles in home cards

* Updated workflows

* Removed deprecated standard appearance

* Updated karma.conf.js

* Fixed  menu link styles

* Resolving codesmells

* Removed unnecessary scss

* Updated appearance component

* Updated ngx-highlightjs and resolved breaking changes

* Fixed configuration button styles

* Fixed sidenav container styles

* feat: update deploy wf (root permissions)

* Updated production script

* Updated package.json

* Added module '@angular/flex-layout'

* Fixed format

* Improved dark styles

* Updated about page

---------

Co-authored-by: Daniel <daniel.grana@imatia.com>

diff --git a/.github/workflows/prepare-release.yml b/.github/workflows/prepare-release.yml
--- a/.github/workflows/prepare-release.yml
+++ b/.github/workflows/prepare-release.yml
@@ -10,16 +10,22 @@ on:
         default: 'minor'
         type: choice
         options:
-          - 'minor'
-          - 'hotfix'
+          - "minor"
+          - "hotfix"
+          - "rc"
+          - "beta"
+      RELEASE_CANDIDATE_VERSION:
+        description: "Release candidate version (e.g. 15.0.0-rc.0)"
+      BETA_VERSION:
+        description: "Beta version (e.g. 15.0.0-beta.0)"
 
 env:
   NPM_REGISTRY: https://registry.npmjs.org/
   CI_EMAIL: ontimize-web@imatia.com
   CI_USERNAME: ontimize-web
-  MAIN_BRANCH: master
-  DEVELOP_BRANCH: 8.x.x
-  
+  MAIN_BRANCH: main.15.x
+  DEVELOP_BRANCH: 15.x.x
+
 jobs:
   build:
     runs-on: ubuntu-20.04
@@ -31,12 +37,57 @@ jobs:
           if [ "${{ github.event.inputs.RELEASE_TYPE }}" = "hotfix" ]; then
             BASELINE_BRANCH=${{ env.MAIN_BRANCH }}
             isHotfix=1
+            isMinor=0
+            isRC=0
+            isBeta=0
+          elif [ "${{ github.event.inputs.RELEASE_TYPE }}" = "rc" ]; then
+            BASELINE_BRANCH=${{ env.DEVELOP_BRANCH }}
+            isHotfix=0
+            isMinor=0
+            isRC=1
+            isBeta=0
+          elif [ "${{ github.event.inputs.RELEASE_TYPE }}" = "beta" ]; then
+            BASELINE_BRANCH=${{ env.DEVELOP_BRANCH }}
+            isHotfix=0
+            isMinor=0
+            isRC=0
+            isBeta=1
           else
             BASELINE_BRANCH=${{ env.DEVELOP_BRANCH }}
             isHotfix=0
+            isMinor=1
+            isRC=0
+            isBeta=0
           fi
           echo "BASELINE_BRANCH=$BASELINE_BRANCH" >> $GITHUB_ENV
           echo "isHotfix=$isHotfix" >> $GITHUB_OUTPUT
+          echo "isMinor=$isMinor" >> $GITHUB_OUTPUT
+          echo "isRC=$isRC" >> $GITHUB_OUTPUT
+          echo "isBeta=$isBeta" >> $GITHUB_OUTPUT
+
+      - name: Setup release candidate version
+        if: ${{ steps.parameters.outputs.isRC == true }}
+        id: release-candidate
+        run: |
+          versionNumber=${{ github.event.inputs.RELEASE_CANDIDATE_VERSION}}
+          if [[ $versionNumber =~ ^[0-9]+\.[0-9]+\.[0-9]+\-rc\.[0-9]+ ]]; then
+            echo "version=${BASH_REMATCH[0]}" >> $GITHUB_OUTPUT
+          else
+            echo "Invalid Release Candidate version"
+            exit 1
+          fi
+
+      - name: Setup Beta version
+        if: ${{ steps.parameters.outputs.isBeta == true }}
+        id: beta
+        run: |
+          versionNumber=${{ github.event.inputs.BETA_VERSION}}
+          if [[ $versionNumber =~ ^[0-9]+\.[0-9]+\.[0-9]+\-beta\.[0-9]+ ]]; then
+            echo "version=${BASH_REMATCH[0]}" >> $GITHUB_OUTPUT
+          else
+            echo "Invalid Beta version"
+            exit 1
+          fi
 
       - name: Checkout merge commit
         uses: actions/checkout@v3
@@ -44,10 +95,10 @@ jobs:
           ref: ${{ env.BASELINE_BRANCH }}
           fetch-depth: 0
 
-      - name: Node 12.x
+      - name: Node 18.x
         uses: actions/setup-node@v3
         with:
-          node-version: 12.13.0
+          node-version: 18.10.0
           registry-url: ${{ env.NPM_REGISTRY }}
 
       - name: obtain package.json version
@@ -62,11 +113,48 @@ jobs:
 
       ## MINOR
       - name: bumping minor version in package.json
-        if: ${{ steps.parameters.outputs.isHotfix == false }}
+        if: ${{ steps.parameters.outputs.isMinor == true }}
         run: |
           version=$(echo "${{ steps.project.outputs.version }}" | sed 's/-SNAPSHOT-[0-9]//')
           npm version $version --no-git-tag-version
           echo "RELEASE_VERSION=$(node -pe "require('./package.json')['version']")" >> $GITHUB_ENV
+
+      - name: bumping minor version in internal package.json
+        if: ${{ steps.parameters.outputs.isMinor == true }}
+        working-directory: .
+        run: |
+          version=$(echo "${{ steps.project.outputs.version }}" | sed 's/-SNAPSHOT-[0-9]//')
+          npm version $version --no-git-tag-version
+
+      ## RELEASE CANDIDATE
+      - name: bumping minor version in package.json
+        if: ${{ steps.parameters.outputs.isRC == true }}
+        run: |
+          version=$(echo "${{ steps.release-candidate.outputs.version }}")
+          npm version $version --no-git-tag-version
+          echo "RELEASE_VERSION=$(node -pe "require('./package.json')['version']")" >> $GITHUB_ENV
+
+      - name: bumping minor version in internal package.json
+        if: ${{ steps.parameters.outputs.isRC == true }}
+        working-directory: .
+        run: |
+          version=$(echo "${{ steps.release-candidate.outputs.version }}")
+          npm version $version --no-git-tag-version
+
+      ## Beta
+      - name: bumping minor version in package.json
+        if: ${{ steps.parameters.outputs.isBeta == true }}
+        run: |
+          version=$(echo "${{ steps.beta.outputs.version }}")
+          npm version $version --no-git-tag-version
+          echo "RELEASE_VERSION=$(node -pe "require('./package.json')['version']")" >> $GITHUB_ENV
+
+      - name: bumping minor version in internal package.json
+        if: ${{ steps.parameters.outputs.isBeta == true }}
+        working-directory: .
+        run: |
+          version=$(echo "${{ steps.beta.outputs.version }}")
+          npm version $version --no-git-tag-version
 
       ## HOTFIX
       - name: bumping hotfix version in package.json
@@ -75,8 +163,14 @@ jobs:
           npm version patch --no-git-tag-version
           echo "RELEASE_VERSION=$(node -pe "require('./package.json')['version']")" >> $GITHUB_ENV
 
+      - name: bumping hotfix version in internal package.json
+        if: ${{ steps.parameters.outputs.isHotfix == true }}
+        working-directory: .
+        run: |
+          npm version patch --no-git-tag-version
+
       - name: Create release branch
-        if: ${{ steps.parameters.outputs.isHotfix == false }}
+        if: ${{ steps.parameters.outputs.isMinor == true }} || ${{ steps.parameters.outputs.isRC == true }} || ${{ steps.parameters.outputs.isBeta == true }}
         run: |
           version=${{ env.RELEASE_VERSION }}
           git checkout -b release/$version
@@ -110,3 +204,4 @@ jobs:
         run: |
           version=${{ env.RELEASE_VERSION }}
           gh pr create -B ${{ env.MAIN_BRANCH }} -H hotfix/$version --title "Hotfix $version" --body "" --draft --label "release"
+
